"""Add verified at in user

Revision ID: 96eb51b6d18e
Revises: ead3217587bf
Create Date: 2026-02-16 19:48:53.440390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96eb51b6d18e'
down_revision: Union[str, Sequence[str], None] = 'ead3217587bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mail_verified_at')
    # ### end Alembic commands ###
